"""
This type stub file was generated by pyright.
"""


"""
    pygments.modeline
    ~~~~~~~~~~~~~~~~~

    A simple modeline parser (based on pymodeline).

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS.
    :license: BSD, see LICENSE for details.
"""
__all__ = ["get_filetype_from_buffer"]
modeline_re = ...

def get_filetype_from_line(l): ...
def get_filetype_from_buffer(buf, max_lines=...):
    """
    Scan the buffer for modelines and return filetype if one is found.
    """
    ...
