name: Build/Test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: "3.14"
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - name: Install dependencies
        run: make install
      - name: Static checks
        run: make static
      - name: Run tests
        env:
          TERM: "dumb"
        run: make test
