name: Publish Docs
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v6
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: "3.14"
      - name: Install Graphviz
        run: |
          if ! command -v dot; then
            sudo apt-get update
            sudo apt-get install -y graphviz
          fi
          dot -V
      - name: Install dependencies
        run: make install
      - name: Make docs site
        run: make docs && ls -la site
      - uses: actions/upload-pages-artifact@v5
        with:
          path: site
      - uses: actions/deploy-pages@v5
        id: deployment
